### ISSUE TITLE
Overbrights do not display correctly in super8.

### ISSUE THREAD

**Issue by WoolieWool** [qbism/super8#1]
Crossposted from https://qbism.com/viewtopic.php?f=1&t=8

I was playing through the first episode of Quake in DOS v1.06 (installed straight from an OEM CD I got with a joystick in 1998) and noticed the lighting in the DOS executable seemed more vibrant than in super8. I took a screenshot in v1.06 and then another in super8 and it seems like super8 does not render overbrights properly, perhaps not at all.

http://i.imgur.com/Dcf7lJT.png
Quake 1.06 (correct)

http://i.imgur.com/w533tRC.png
Makaqu 1.4 (correct)

http://i.imgur.com/tj1P8t3.png
Qbism super8 (incorrect, also the full status bar with background "squashes" the view area, stretching everything horizontally)

**Comment by qbism** [comment]
This one I can't explain... in fact 'too bright/ washed out' is usually the issue recently.  Please try clearing out the config and reinstalling /super8 folder from the latest version.  (Confirm v236).  Also, what is the effect of adjusting gamma cvar?  I usually play at 0.9.

**Comment by WoolieWool** [comment]
See: https://qbism.com/viewtopic.php?f=1&t=8&p=21#p21

The people who say it's too bright are probably using s8pal as their palette, instead of the classic palette. In default it's definitely not rendering overbrights, and a clean install doesn't affect it. Neither does gamma (I use 1.0, and changed it to 0.9, and then back)

The SSG distortion is caused by incorrect default view model offsets. I posted corrected offsets in the thread. The SSG model should slide beneath the camera and off the screen at the apex of its firing animation, with the default offset it slams straight into the camera, causing the distortion. I would suggest removing the custom weapon models and turning lerping off when testing the view offset--that way you can compare them frame by frame against other ports, and I noticed the high-poly super8 SSG is more forgiving--an scr_ofsx of 2 fixes it, while 2.5 is necessary to fix the vanilla SSG.

**Comment by qbism** [comment]
Agreed that the original Quake palette looks dark with this engine, which is why the s8pal was created.  Indeed it's largely due to dampened overbrights as a compromise to the increased brightness trend of newer maps.  Many still appear washed-out without adjusting gamma.  It is what it is.
