### ISSUE TITLE
Super shotgun distorts/clips into screen during firing animation

### ISSUE THREAD

**Issue by WoolieWool** [qbism/super8#3]
https://www.youtube.com/watch?v=0vvW-cDbfjg

In this playthrough I did of E2M6 in super8 you can clearly see the super shotgun's geometry distort during the firing animation--it appears to be clipping directly into the screen. This happens with both the stock super shotgun model and the hi-poly model included with super8 (which I had removed in an attempt to see if that would make the issue go away--it did not).

**Comment by qbism** [comment]
The viewport is so close to the model that it is clipping through it and showing interior faces.  I suspect you have old super8 versions or modified screen offset settings.
Delete (or backup) config and super8 directory, then reinstall the super8 dir from zip.
If that doesn't correct it, you will need to manually adjust scr_ofsx, y, z cvars.

**Comment by qbism** [comment]
BTW, there are also weapon-bob cvars that may affect clipping.  Since this can be adjusted via cvars I closed this issue.

**Comment by leilei-** [comment]
this is normal behavior in quake with a sbar/ibar as that fudges the weapon upward.  yes quake shipped with weapon models clipping.  yes quake was rushed and yes quake is full of hacks

**Comment by qbism** [comment]
Heh, 'fixing' a hack is sometimes stretching a skin that is already thin.  A new break or incompatibility may emerge.  This particular issue is affected by monitor resolution, vwep mods, etc.

**Comment by leilei-** [comment]
in normal quake it's most eregious with a tweaked VGA mode i.e. 320x480
