### ISSUE TITLE
Arcane Dimensions compatibility?

### ISSUE THREAD

**Issue by L3gend** [qbism/super8#4]
Was hoping to be able to play the new Arcane Dimensions mod on Qbism, but when I try to start it, the game just autocloses. Not sure if this is an engine side issue which can be resolved, or a mod side issue which they have to choose to remedy. 

btw, I cannot seem to get access to the new site. Which is the best way to communicate about super8?

**Comment by qbism** [comment]
I haven't tried that mod yet.  I'll take a look when I can, but some mods targeting only a specific engine won't work on other engines.

Try the forum on qbism.com.

**Comment by L3gend** [comment]
thanks for the reply. I figured arcane dimensions working in qbism would be a long shot. but was hoping anyways. qbism runs the best for me and is my favorite engine. 
Regarding qbism.com, I can't seem to access it for some reason. It won't load for me. 
btw, does qbism super8 have a console command similar to qbism super8 cl_beams_quakepositionhack? for darkplaces? I am trying to adjust the position of the lightening gun beam in QC but no matter what I do, it is always in the center when using qbism super8. I was wondering if it is the result of qbism also having a console variable similar to qbism super8 cl_beams_quakepositionhack? in dark places that I need to disable in order to get it to work. I've looked for one. but no luck so far.
I'm trying to make a progs that will work with the quake 1.5 weapon models that fixes the projectile positions. I've fixed everything except the lightening gun. But when I run it in qbism compared to dark places, the lightening gun beam always seems to come from exactly the middle of the player. Is this something that is hard coded into super8?

Date: Tue, 29 Dec 2015 10:13:27 -0800

**Comment by qbism** [comment]
Guilty as charged... From cl_tent.c    // if coming from the player, update the start position     if (b->entity == cl.viewentity)     {           // Manoel Kasimier - begin          // This keeps the angle of the beam identical to the viewangle          if (b->model->name[10] == '2' /_"progs/bolt2.mdl"_/) // bloody hack         {               vec3_t  front, right, up;               VectorSubtract (b->start, b->end, dist);                forward = Length(dist);             AngleVectors (r_refdef.viewangles, front, right, up);               VectorCopy (cl_entities[cl.viewentity].origin, b->start);               b->end[0] = b->start[0] + front[0]_forward;             b->end[1] = b->start[1] + front[1]_forward;             b->end[2] = b->start[2] + front[2]*forward;         }           else            // Manoel Kasimier - end            VectorCopy (cl_entities[cl.viewentity].origin, b->start);       }I'm busy with another project, but will add 'to-do' next time engine is updated: cvar_t cl_beams_quakepositionhack = {CVAR_SAVE, "cl_beams_quakepositionhack", "1", "makes your lightning gun appear to fire from your waist (as in Quake and QuakeWorld)"};

-------- Original Message --------
Subject: Re: [super8] Arcane Dimensions compatibility? (#4)

**Comment by qbism** [comment]
Re-saving the mdl files in progs out of Noesis seems to fix this issue.  There's something about the way original AD models were saved that software engines don't like.  Link:  https://qbism.com/download/file.php?id=29

In any case, can't hope to support any mod X for any engine Y so closing this issue.

**Comment by L3gend** [comment]
Thanks. The download link didn't work at first. seems I have to use a proxy site in order to access the download or your qbism.com website.  Not sure why that is. I live in antioch ca usa and using google chrome.
Anyways, got it downloaded and seems to be working fine now so far. Except test map 11. doesn't show the stat numbers changing on the wall when hitting the enemies. 
Just curious, I noticed that you did not replace all the models in the progs folder. was it just because they did not all need to be replaced? 

Date: Wed, 30 Dec 2015 18:06:41 -0800

**Comment by qbism** [comment]
Not sure about website issue.  Other people have been able to access and download.

I think I replaced all mdls.  I see 284 mdl files in the AD/progs folder.  Can you tell what's missing?  

Possibly should have only replaced the problem models... I see that misc_digit is missing skins.  Will take a look.

**Comment by L3gend** [comment]
I was looking at the files closer. It looks like it was the .spr files that were missing. Not the models. Sorry about that. 

Date: Fri, 1 Jan 2016 09:52:54 -0800

**Comment by qbism** [comment]
OK, cool.  Did you try the updated progs download?  These include all the skins.

-------- Original Message --------
Subject: Re: [super8] Arcane Dimensions compatibility? (#4)

**Comment by L3gend** [comment]
I didn't see the updated ones. Is it on the quakeone forum or the qbism site? I only got the first one you sent me through email. 

Date: Sun, 3 Jan 2016 15:44:17 -0800

**Comment by qbism** [comment]
Yesterday I you a new direct link via email.

-------- Original Message --------
Subject: Re: [super8] Arcane Dimensions compatibility? (#4)

**Comment by L3gend** [comment]
Thanks. I missed the link you sent me since it ended up in my spam folder for some reason. Anyways, I got it. I haven't had to check it out yet but definitely will a bit later tonight. 
Thanks again. 

Date: Wed, 6 Jan 2016 12:04:31 -0800
