### ISSUE TITLE
Crashing when increasing status bar scaling

### ISSUE THREAD

**Issue by L3gend** [qbism/super8#5]
When I try to increase the status bar scaling all the way up, the game crashes. Winxp sp3.

**Comment by qbism** [comment]
What screen resolution causes the crash, or is it all resolutions?  Crashes in windowed mode?

**Comment by L3gend** [comment]
it seems to crash when playing in 600x800 resolution with satus bar scaling all the way up in full screen mode. 
also, the weapon models seem to be way below view. can barely see the tip of the ssg. how would I move them up so I can see more of them?

Date: Tue, 29 Dec 2015 21:51:20 -0800

**Comment by qbism** [comment]
I was not able to duplicate this in Win7 or Linux/Wine, and xp is not supported.  Closing issue.

Use negative values of scr_ofsx or z.
