### ISSUE TITLE
Windows Taskbar problem

### ISSUE THREAD

**Issue by ZerTerO** [qbism/super8#7]
Hy. If you have the Windows Taskbar (W7 W10) on the left side, or on the top (not below), then you see always the taskbar in the game if you play in fullscreen...

**Comment by qbism** [comment]
I'll try to duplicate this when I get a chance.  Windows API function ChangeDisplaySettings is used to go fullscreen.   Does this happen to you on other Quake engines or other games?

**Comment by ZerTerO** [comment]
No, only with qbism Super8. With different computers und different Windows os (10 and 7). But you get this only, if you use the task bar on the left side or on the top of the screen. Right side or, as always, below, you dont see the taskbar. I wanted to useyour port (it is a GREAT  port!), but would not change my habit to have the taskbar on the left. ;o)
 

Gesendet: Donnerstag, 30. März 2017 um 19:17 Uhr
Von: qbism <notifications@github.com>
An: qbism/super8 <super8@noreply.github.com>
Cc: ZerTerO <zertero@web.de>, Author <author@noreply.github.com>
Betreff: Re: [qbism/super8] Windows Taskbar problem (#7)


I'll try to duplicate this when I get a chance. Windows API function ChangeDisplaySettings is used to go fullscreen. Does this happen to you on other Quake engines or other games?

**Comment by qbism** [comment]
I was able to duplicate this on Win7.  Interesting that it does not occur when the taskbar is on the right side, only the left.

**Comment by ZerTerO** [comment]
Dont forget the top side... ;)

Gesendet: Mittwoch, 05. April 2017 um 04:31 Uhr
Von: qbism <notifications@github.com>
An: qbism/super8 <super8@noreply.github.com>
Cc: ZerTerO <zertero@web.de>, Author <author@noreply.github.com>
Betreff: Re: [qbism/super8] Windows Taskbar problem (#7)


I was able to duplicate this on Win7. Interesting that it does not occur when the taskbar is on the right side, only the left.

**Comment by qbism** [comment]
The topside is a 'feature' ;)
What's maddening is that the bar is overlaid as if intentional - and only when left and top - but so far I don't see a distinction in code. 
 I plan to see if an earlier build does not have this bug and find the difference.

**Comment by qbism** [comment]
Follow-up:  The bug happens in both new and previous builds.  I was unable to identify anything in the video mode code that should affect the taskbar;  the actual mode commands look like Windows SDK example code.
Doing a little more internet digging, a similar left-or-top issue was reported on an older build of UE4:  https://answers.unrealengine.com/questions/561725/fullscreen-problems-when-windows-bar-is-on-left-or.html   I couldn't find anything to say if it is resolved or not in a later build.  Several games have bug reports of blank pixels where the taskbar would be and an off-center game screen with taskbar at top or left.  No solutions, though, just work-arounds and speculation.  (Is it a dev issue or a Windows issue?)
I'm closing this and slapping on a 'wontfix' label but 'cantfix' is more accurate.
