### ISSUE TITLE
The README text is gambled and can't be read properly in github

### ISSUE THREAD

**Issue by teiman** [qbism/super8#9]
OH GOD is beatiful!
https://www.youtube.com/watch?v=B8K1aB4oQPA
I just found this video of the engine. Is amazing. Is better than I imagined.   I trough a software renderer would look dirty, ofuscated, like a bunch of pixels mixed, but it looks amazing cool. And faithfull to the original!

Also, yea, the readme. don't seems to have the md format, so appear withouth line feeds in github.
You 100% need to add this youtube video to the desciption.  You did some amazing cool work here, mr. qBism!.

**Comment by qbism** [comment]
Glad you enjoy it!  Yeah, that Vondur map looks great, video compression doesn't do it justice.

I probably won't touch this project again in it's current form.  Even the readme has suffered from "digital decay".  If anything I would rebuild it as fork of some other engine that is more recently maintained.

**Comment by eGax** [comment]
It has ran fine under wine, but if a redo ever happens wishful thinking it's based off a fork from an engine that supports Linux. ;-)

**Comment by qbism** [comment]
finally fixed the readme LOL
